wallpaper {
    monitor =
    # path = ~/Pictures/Wallpapers/
    # path = ~/Pictures/GoodWalls/wallhaven-gwqxl7_1920x1080.png
    path = ~/Pictures/GoodWalls/wallhaven-ymp23d_2130x1197.png
    fit_mode = cover
    timeout = 300
}
