# Video

profile=high-quality hwdec=auto

# Window

autofit-larger=90%x90%

# Audio

volume=70

# ⏱ Resume playback

save-position-on-quit=no

# Subtitles

sub-auto=all sub-font-size=20 sub-border-size=1

# UI

osd-level=3 osd-font-size=20 osd-bar=yes

# ⚡ Cache (for YouTube etc)

cache=yes demuxer-max-bytes=100M demuxer-readahead-secs=10

